name: Deploy mdBooks to GitHub Pages

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  # Detect changes in each subcrate
  changes:
    runs-on: ubuntu-latest
    outputs:
      # List of changed mdbooks
      books: ${{ steps.get-packages.outputs.books }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            aptos:
              - 'aptos/docs/**'
            ethereum:
              - 'ethereum/docs/**'
            kadena:
              - 'kadena/docs/**'
      - name: Get list of changed packages
        id: get-packages
        run: |
          BOOKS=$(echo '${{ steps.filter.outputs.changes }}' | jq -c '.')
          echo "books=$BOOKS" | tee -a "$GITHUB_OUTPUT"

  build:
    needs: changes
    if: ${{ needs.changes.outputs.books != '[]' && needs.changes.outputs.books != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Parse JSON array containing names of all changed light client mdbooks,
        # e.g. ['aptos', 'ethereum', 'kadena'] if the `aptos`, `ethereum` and `kadena` mdbooks contain changes.
        light-client: ${{ fromJSON(needs.changes.outputs.books) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@mdbook
      - run: mdbook build
        working-directory: ${{ github.workspace }}/${{ matrix.light-client }}/docs
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ matrix.light-client }}
          path: ${{ matrix.light-client }}/docs/book
          retention-days: 1

  deploy:
    needs: [changes, build]
    if: ${{ (github.ref_name == 'dev' && github.event_name == 'push') && (needs.changes.outputs.books != '[]' && needs.changes.outputs.books != '') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Parse JSON array containing names of all changed light client mdbooks,
        # e.g. ['aptos', 'ethereum', 'kadena'] if the `aptos`, `ethereum` and `kadena` mdbooks contain changes.
        light-client: ${{ fromJSON(needs.changes.outputs.books) }}
    permissions:
      contents: write
    steps:
      - name: Create publish dir
        run: mkdir -p public
        working-directory: ${{ github.workspace }}
      - name: Download `${{ matrix.light-client }}` book artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.light-client }}
          path: ./public
      - run: |
          ls public
      - name: Deploy mdbook
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/${{ matrix.light-client }}
          destination_dir: ${{ matrix.light-client }}
